-- =========================================================
-- Migration 001 - Initial Schema
-- Motiva Platform
-- =========================================================


-- =========================================================
-- Table: inspections
-- Stores the main data for each vegetation inspection
-- =========================================================

CREATE TABLE inspections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    latitude DOUBLE PRECISION NOT NULL
        CHECK (latitude BETWEEN -90 AND 90),

    longitude DOUBLE PRECISION NOT NULL
        CHECK (longitude BETWEEN -180 AND 180),

    status VARCHAR(20) NOT NULL
        CHECK (status IN ('OK', 'ATENÇÃO', 'URGENTE')),

    confidence DOUBLE PRECISION NOT NULL
        CHECK (confidence BETWEEN 0 AND 1),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =========================================================
-- Table: detections
-- Stores detections associated with each inspection
-- =========================================================

CREATE TABLE detections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    inspection_id BIGINT NOT NULL,

    class_name VARCHAR(100) NOT NULL,

    confidence DOUBLE PRECISION NOT NULL
        CHECK (confidence BETWEEN 0 AND 1),

    x INTEGER NOT NULL,

    y INTEGER NOT NULL,

    width INTEGER NOT NULL
        CHECK (width >= 0),

    height INTEGER NOT NULL
        CHECK (height >= 0),

    CONSTRAINT fk_detection_inspection
        FOREIGN KEY (inspection_id)
        REFERENCES inspections(id)
        ON DELETE CASCADE
);